/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_5986A5E__
#define __PLUGINEDITOR_H_5986A5E__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class PluginTestAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    PluginTestAudioProcessorEditor (PluginTestAudioProcessor* ownerFilter);
    ~PluginTestAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_5986A5E__
